{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "laminar.componentName" (dict "root" . "component" "postgres") }}
  labels:
{{ include "laminar.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.postgres.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
---
{{- end }}
{{- if .Values.clickhouse.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "laminar.componentName" (dict "root" . "component" "clickhouse") }}
  labels:
{{ include "laminar.componentLabels" (dict "root" . "component" "clickhouse") | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.clickhouse.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.clickhouse.persistence.size }}
---
{{- end }}
{{- if .Values.quickwit.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "laminar.componentName" (dict "root" . "component" "quickwit") }}
  labels:
{{ include "laminar.componentLabels" (dict "root" . "component" "quickwit") | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.quickwit.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.quickwit.persistence.size }}
{{- end }}
